## Machine Learning in Python

In [ ]:
# Importing Necessary Libraries:

In [1]:
import pandas as pd
from sqlalchemy import create_engine

### Functions and Getting Help

In [43]:
# The Use of help
#help(help)
import math
#help(math) # This module provides access to the mathematical functions defined by the C standard.
#help(str)
import datetime
#help(datetime.datetime)

In [40]:
# Defining functions
def happy_birthday(name, age):
    #print("Happy birthday to you" +' '+ (name)+'!') # or
    print("Happy birthday to you",(name)+'!')
    print("You are", (age), 'years old.')
    
happy_birthday('Michael', 20)

Happy birthday to you Michael!
You are 20 years old.

In [44]:
# Example of Functions that don't return
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    min(diff1, diff2, diff3)
    
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7),
)

None None None

In [ ]:
# Functions Applied to Functions; here 'mult_by_five' is applied to 'call'
def mult_by_five(x):
    return 5 * x

def call(fn, arg):
    """Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1), 
    sep='\n', # '\n' is the newline character - it starts a new line
)

### Booleans and Conditionals

In [50]:
# Simple booleans Check:
x = True
print(x)
print(type(x))

True
<class 'bool'>

In [51]:
# Comparison Operations:
def can_run_for_president(age):
    """Can someone of the given age run for president in the US?"""
    # The US Constitution says you must be at least 35 years old
    return age >= 35

print("Can a 19-year-old run for president?", can_run_for_president(19))
print("Can a 45-year-old run for president?", can_run_for_president(45))

Can a 19-year-old run for president? False
Can a 45-year-old run for president? True

In [52]:
# Boolean conversion:
print(bool(1)) # all numbers are treated as true, except 0
print(bool(0))
print(bool("asf")) # all strings are treated as true, except the empty string ""
print(bool(""))
# Generally empty sequences (strings, lists, and other types we've yet to see like lists and tuples)
# are "falsey" and the rest are "truthy"

True
False
True
False

### Lists

In [ ]:
# TBC later

### Loops and List Comprehensions

In [56]:
# For loop Examples:
# Example ONE
'''planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets:
    print(planet, end=' ') # print all on same line'''


# Example TWO:
'''multiplicands = (2, 2, 2, 3, 3, 5)
product = 1
for mult in multiplicands:
    product = product * mult
product'''

# Example THREE:
s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''
# print all the uppercase letters in s, one at a time
for char in s:
    if char.isupper():
        print(char, end='')

HELLO

In [60]:
# While loop Examples:
# Example ONE
'''i = 0
while i < 10:
    print(i, end=' ')
    i += 1 # increase the value of i by 1'''

# Example TWO
'''total = 0
j = 1
while j < 5:
    total += j
    j += 1
print(total)'''

# Example THREE:
given_list = [5, 4, 4, 3, 1, -2, -3, -5]
total = 0
i = 0

while given_list[i] > 0:
    total += given_list[i]
    i += 1
print(total)

17

In [83]:
# List Compehension:

# Intial List Iteration:
'''doubles = []
for x in range(1, 11):
    doubles.append(x*2)
print(doubles)'''

# Comprehension Version:
'''doubles = [x*2 for x in range(1, 11)]
print(doubles)'''

# Example (2)
'''fruits = ['mango', 'orange', 'lemon', 'apple']
fruits = [fruit.upper() for fruit in fruits]
print(fruits)'''
# or 
'''fruits = [fruit.upper() for fruit in ['mango', 'orange', 'lemon', 'apple']]
print(fruits)'''

# Example (3)
'''fruit_chars = [fruit[0] for fruit in ['mango', 'orange', 'lemon', 'apple']]
print(fruit_chars)'''


# List Comprehension & IF Conditions:
'''numbers = [1, -2, 3, -4, 5, -6, 8, -7]
#positive_nums = [num for num in numbers if num >= 0]
#negative_nums = [num for num in numbers if num < 0]
even_nums = [num for num in numbers if num % 2 == 0]
odd_nums = [num for num in numbers if num % 2 == 1]
print(odd_nums)'''

grades = [80, 42, 79, 90, 56, 61, 30]
passing_grades = [grade for grade in grades if grade >= 60]
print(passing_grades)

[80, 79, 90, 61]

### Strings and Dictionaries

In [90]:
# https://www.youtube.com/watch?v=tb6EYiHtcXU
name = input("Enter your name: ")
#result = len(name) 
result = name.find("o")
print(result)

Enter your name:  Agboko Toyovi

3

### Indexing, Selecting & Assigning

In [ ]:
# TO MOVE SECTION TO PANDAS

In [24]:
import pandas as pd
import numpy as np

In [28]:
df1 = pd.read_csv('/Users/micha/OneDrive/Desktop/Social_Network_Ads.csv')
df1.head()
#, index_col='User ID'

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [12]:
#df.loc[0:3, ['Age']]

In [31]:
#df.iloc[[2,3][1,2]]

In [15]:
age = df['Age']
age

User ID
15624510    19
15810944    35
15668575    26
15603246    27
15804002    19
            ..
15691863    46
15706071    51
15654296    50
15755018    36
15594041    49
Name: Age, Length: 400, dtype: int64

In [54]:
df2 = pd.read_csv('/Users/micha/OneDrive/Desktop/artists.csv', encoding='latin1')
df2.head()

,idnumber,name,artist_bio,nationality,gender,begin_date,end_date
0,11,Jean (Hans) Arp,"French, born Germany (Alsace). 18861966",French,male,28/02/1905,19/05/1905
1,19,Richard Artschwager,"American, 19232013",American,male,06/04/1905,05/07/1905
2,34,Alvar Aalto,"Finnish, 18981976",Finnish,male,12/03/1905,29/05/1905
3,38,Magdalena Abakanowicz,"Polish, 19302017",Polish,female,13/04/1905,09/07/1905
4,60,Ansel Adams,"American, 19021984",American,male,16/03/1905,06/06/1905

In [37]:
df2.loc[:,['name','nationality']]

                     name nationality
0         Jean (Hans) Arp      French
1     Richard Artschwager    American
2             Alvar Aalto     Finnish
3   Magdalena Abakanowicz      Polish
4             Ansel Adams    American
..                    ...         ...
95     Alberto Giacometti       Swiss
96            Sam Gilliam    American
97         Allen Ginsberg    American
98            John Giorno    American
99      Alberto Gironella     Mexican

[100 rows x 2 columns]

In [39]:
#df2.loc['Richard Artschwager']
df2.loc[1]

innumber                        19
name           Richard Artschwager
artist_bio     American, 19232013
nationality               American
gender                        male
begin_date              06/04/1905
end_date                05/07/1905
Name: 1, dtype: object

In [41]:
# Selecting by index & column titles:
# Label-based Selection
df2.loc[[1, 95],['name','nationality']]

                   name nationality
1   Richard Artschwager    American
95   Alberto Giacometti       Swiss

In [45]:
# Index-based selection:
df2.iloc[[2,4],[1,3]]

          name nationality
2  Alvar Aalto     Finnish
4  Ansel Adams    American

In [56]:
#df2[df2.nationality == 'French']
df2[df2.idnumber < 100]

,idnumber,name,artist_bio,nationality,gender,begin_date,end_date
0,11,Jean (Hans) Arp,"French, born Germany (Alsace). 18861966",French,male,28/02/1905,19/05/1905
1,19,Richard Artschwager,"American, 19232013",American,male,06/04/1905,05/07/1905
2,34,Alvar Aalto,"Finnish, 18981976",Finnish,male,12/03/1905,29/05/1905
3,38,Magdalena Abakanowicz,"Polish, 19302017",Polish,female,13/04/1905,09/07/1905
4,60,Ansel Adams,"American, 19021984",American,male,16/03/1905,06/06/1905
5,94,Munira Al-Kazi,"Kuwaiti, born 1939",Kuwaiti,female,22/04/1905,NaN

### Working with External Libraries

### Integrating MySQL

In [6]:
pip install ipython-sql sqlalchemy psycopg2

Requirement already satisfied: ipython-sql in c:\users\micha\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: sqlalchemy in c:\users\micha\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: psycopg2 in c:\users\micha\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: prettytable in c:\users\micha\anaconda3\lib\site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in c:\users\micha\anaconda3\lib\site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlparse in c:\users\micha\anaconda3\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\users\micha\anaconda3\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\micha\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\micha\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\micha\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: decorator in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\micha\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\micha\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\micha\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing in c:\users\micha\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\micha\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\micha\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%load_ext sql

# For your PostgreSQL (Mac/TablePlus setup):
%sql postgresql://postgres:your_password@localhost:5432/ng_lms

# (Or if you switch to MySQL later):
# %sql mysql+pymysql://user:pass@localhost/db_name

Traceback (most recent call last):
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 3298, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\micha\anaconda3\Lib\site-packages\sql\magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
        connect_str,
    ...<2 lines>...
        creator=args.creator,
    )
  File "C:\Users\micha\anaconda3\Lib\site-packages\sql\connection.py", line 70, in set
    cls.current = existing or Connection(descriptor, connect_args, creator)
                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sql\connection.py", line 55, in __init__
    self.internal_connection = engine.connect()
                               ~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 3274, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        err, dialect, engine
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 2439, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\base.py", line 3298, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 1264, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 713, in checkout
    rec = pool._do_get()
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 675, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 901, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\pool\base.py", line 897, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\create.py", line 646, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\sqlalchemy\engine\default.py", line 622, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\anaconda3\Lib\site-packages\psycopg2\__init__.py", line 135, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/20/e3q8)

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [3]:
%load_ext sql
%sql postgresql://postgres:apprendre22@localhost:5432/ng_lms

In [12]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Setup the connection
# Replace 'your_password' with your actual password
engine = create_engine('postgresql://postgres:apprendre22@localhost:5432/ng_lms')

# 2. Run the query and store it in a 'DataFrame' (like a built-in Excel sheet)
try:
    df = pd.read_sql("SELECT * FROM students LIMIT 3;", engine)
    print("Success! Here are your first 3 students:")
    print(df)
except Exception as e:
    print(f"Still having trouble: {e}")

Success! Here are your first 3 students:
   student_id first_name     last_name                          email  \
0      328412    Richard   Artschwager      Richard.Artschwager@sd.to
1      874131     Alvar          Aalto             AlvarAalto@kdss.ht
2      642607  Magdalena   Abakanowicz  Magdalena.Abakanowicz@sad.com

  enrollment_date
0      1905-05-19
1      1905-07-05
2      1905-05-29

### AI Amended Codes for NG LMS Schema Items

In [ ]:
# 1. Organisation Table (Create this first so others can reference it)
CREATE TABLE organisation (
    orgid VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    telephone VARCHAR(20) # Use VARCHAR for phones to handle leading zeros
);

# 2. Users Table
CREATE TABLE users (
    employee_number INT PRIMARY KEY,
    ni_number VARCHAR(9),      
    title VARCHAR(50),              
    first_name VARCHAR(250),
    preferred_name VARCHAR(250),    
    last_name VARCHAR(250),
    dob DATE,
    email_address VARCHAR(250) UNIQUE,
    position_title VARCHAR(250),
    user_role VARCHAR(100), # Renamed from 'Role' to avoid reserved word
    staff_group VARCHAR(250),              
    division VARCHAR(250),
    org_unit_group VARCHAR(250), # Renamed from 'Group'
    directorate VARCHAR(250),
    department_id VARCHAR(20) REFERENCES organisation(orgid), # FOREIGN KEY
    location VARCHAR(250)
);      

# 3. Course Table 
CREATE TABLE course (
    courseid VARCHAR(20) PRIMARY KEY,
    title VARCHAR(250),
    status VARCHAR(50),
    visibility VARCHAR(50),
    length_minutes INT,
    start_date DATE
);

# 4. Classes Table
CREATE TABLE class (
    classid VARCHAR(20) PRIMARY KEY,
    courseid VARCHAR(20) REFERENCES course(courseid), # FOREIGN KEY: Links class to a course
    class_type VARCHAR(50),
    start_date DATE,
    capacity INT
);

# 5. Enrolment Table
CREATE TABLE enrolment (
    enrolid VARCHAR(20) PRIMARY KEY,
    employee_number INT REFERENCES users(employee_number), # FOREIGN KEY: Links to User
    courseid VARCHAR(20) REFERENCES course(courseid),     # FOREIGN KEY: Links to Course
    enrolment_date DATE,
    status VARCHAR(50)
);

In [7]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# wget http://www.gutenberg.org/cache/epub/19337/pg19337.txt

In [1]:
# python3 loadbook.py

In [3]:
import json

data = {"id": 1, "name": "Gemini", "role": "AI"}

# Saving to a local file
with open('api_data.json', 'w') as f:
    json.dump(data, f)

In [4]:
data

{'id': 1, 'name': 'Gemini', 'role': 'AI'}