In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import joblib
from sklearn import tree

In [9]:
#df = pd.read_csv(r'C:\Users\micha\OneDrive\Desktop\video game sales.csv')
#df = pd.read_csv('video game sales.csv')
#df.head()

In [3]:
# Importing Original Data
df = pd.read_csv('music.csv')
df.head()

   age  gender   genre
0   20       1  HipHop
1   23       1  HipHop
2   25       1  HipHop
3   26       1    Jazz
4   29       1    Jazz

In [4]:
# Creating the Input set & Output set
X = df.drop(columns=['genre'])
X.head() # Input set

   age  gender
0   20       1
1   23       1
2   25       1
3   26       1
4   29       1

In [5]:
# Output Data:
y = df['genre'] # Output set
y.head()

0    HipHop
1    HipHop
2    HipHop
3      Jazz
4      Jazz
Name: genre, dtype: object

In [6]:
# Preparing model using an algorithm:
model = DecisionTreeClassifier() # New instance of DecisionTreeClassifier class
model.fit(X, y) # Training the new model to learn patterns in our data
predictions = model.predict([ [21, 1], [22, 0] ]) # Predicting results
predictions

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['HipHop', 'Dance'], dtype=object)

In [7]:
# Measuring our model's Accuracy:
# (1) Splitting data into train & test:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

# (2) Training the model
model.fit(X_train, y_train)

# (3) Testing the model
predictions = model.predict(X_test)

# (4) Actual accuracy calculation
score = accuracy_score(y_test, predictions)
score

1.0

In [10]:
# Saving & Loading Models:
%pip install joblib

#joblib.dump(model, 'music-recommender.joblib')

Requirement already satisfied: joblib in c:\users\micha\anaconda3\lib\site-packages (1.4.2)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install joblib

Requirement already satisfied: joblib in c:\users\micha\anaconda3\lib\site-packages (1.4.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
joblib.dump(model, 'music-recommender.joblib')

['music-recommender.joblib']

In [15]:
# All-in-One from Gemini AI:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib

# 1. Load your data
music_data = pd.read_csv('music.csv')
X = music_data.drop(columns=['genre'])
y = music_data['genre']

# 2. Create and Train the model
model = DecisionTreeClassifier()
model.fit(X, y)

# 3. Save the "Brain" immediately
joblib.dump(model, 'music-recommender.joblib')

print("Success! The model is trained and saved as music-recommender.joblib")

Success! The model is trained and saved as music-recommender.joblib

In [12]:
# Reloading the model:
model = joblib.load('music-recommender.joblib')
predictions = model.predict([ [22, 0] ])
predictions

C:\Users\micha\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Dance'], dtype=object)